config/routes.rb
Rails.application.routes.draw do

  #セッション
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  #ユーザー
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'

  #トップページ
  get 'toppages/index'

  #ランキング
  get 'rankings/middle', to: 'rankings#middle'

  #root
  root to: 'toppages#index'

  #ログイン・ログアウト
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #新規登録
  get 'signup', to: 'users#new'

  resources :users, only: [:index, :show, :new, :create]
  resources :middles
  resources :commonnames
  resources :mrs
  resources :surnames
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commonname.rb
class Commonname < ApplicationRecord
  validates :commonname, presence: true, length: { maximum: 255 }
  #使われた回数を昇順表示
  def self.ranking
    Middle.group(:commonname_id).order('count_commonname_id DESC').limit(5).count(:commonname_id)
  end
end

app/models/middle.rb
class Middle < ApplicationRecord
  #userモデルとのリレーション
  belongs_to :user
end

app/models/mr.rb
class Mr < ApplicationRecord
  validates :mr, presence: true, length: { maximum: 255 }
  
  #使われた回数を昇順表示
  def self.ranking
    Middle.group(:mr_id).order('count_mr_id DESC').limit(2).count(:mr_id)
  end

end

app/models/surname.rb
class Surname < ApplicationRecord
  validates :surname, presence: true, length: { maximum: 255 }
  #使われた回数を昇順表示
  def self.ranking
    Middle.group(:surname_id).order('count_surname_id').limit(5).count(:surname_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  #メールアドレスを小文字で保存
  before_save { self.email.downcase! }
  #名前・メールの設定
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  #Middleモデルとのリレーション
  has_many :middles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #helperの導入
  include SessionsHelper

  #privateメソッド
  private

  #ログインの確認
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/middles_controller.rb
class MiddlesController < ApplicationController
  #ログインの確認
  before_action :require_user_logged_in
  #共通メソッドを実行
  before_action :set_middle, only: [:edit, :update, :destroy]

  def index
    @middle = current_user.middles.last
    @middles = current_user.middles
  end

  def show
    @middle = current_user.middles.last
    @middles = current_user.middles
  end

  def new
    @middle = Middle.new
    #ランダムに値を習得
    @commonname = Commonname.where( 'id >= ?', rand(Commonname.first.id..Commonname.last.id) ).first
    @mr = Mr.where( 'id >= ?', rand(Mr.first.id..Mr.last.id) ).first
    @surname = Surname.where( 'id >= ?', rand(Surname.first.id..Surname.last.id) ).first
  end

  def create
    @middle = current_user.middles.build(middle_params)

    if @middle.save
      flash[:success] = '作成成功！'
      redirect_to middles_path
    else
      flash.now[:danger] = '作成失敗！'
      render :new
    end
  end

  def destroy
    @middle.destroy
    flash[:success] = 'ミドルネームは正常に削除されました'
    redirect_to root_url
  end

  def set_middle
    @middle = current_user.middles.find_by(id: params[:id])
    unless @middle
      redirect_to root_url
    end
  end

  def middle_params
    params.require(:middle).permit(:Lname,:Fname,:mr,:surname,:commonname,:commonname_id,:surname_id,:mr_id)
  end

end

app/controllers/mrs_controller.rb
class MrsController < ApplicationController
end

app/controllers/rankings_controller.rb
#ランキングクラス
class RankingsController < ApplicationController
  def middle
    #氏の使われた回数
    @ranking_mr_counts = Mr.ranking
    @mrs = Mr.find(@ranking_mr_counts.keys)
    
    #カバネの使われた回数
    @ranking_surname_counts = Surname.ranking
    @surnames = Surname.find(@ranking_surname_counts.keys)
    
    #俗称の使われた回数
    @ranking_commonname_counts = Commonname.ranking
    @commonnames = Commonname.find(@ranking_commonname_counts.keys)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  #ログインメソッド
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  #ログアウトメソッド
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  #ログイン処理
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
end

app/controllers/surnames_controller.rb
class SurnamesController < ApplicationController
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
  end

  def show
    @user = User.find(params[:id])
    @middles = current_user.middles
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/middles_helper.rb
module MiddlesHelper
  
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #現在ログインしているユーザを取得
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #ログインしているか確認
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #グラファイターの設定
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
  
  
end

app/views/layouts/_card_messages.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">John Smith</p>
      </div>
    </div>
    <div class="content">
      <br>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<%#エラーメッセージの表示%>
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<%#フラッシュメッセージ%>
<% flash.each do |message_type, message| %>
    <div class="notification is-info"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="content has-text-centered">
    <p>
      <strong>JapaneseMiddleName</strong>  by <a href="https://portfolio-white-flag.herokuapp.com/" target="_blank">Kurohata</a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
      <% if logged_in? %>
        <%= link_to user_path(current_user) do %>
          <%= image_tag 'JapaneseMiddleName.png', :width => '112', :height => '28'%>
        <% end %>
      <% else %>
        <%= link_to root_path, data: {"turbolinks" => false} do %>
          <%= image_tag 'JapaneseMiddleName.png', :width => '112', :height => '28'%>
        <% end %>
      <% end %>
    </div>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%#ログインの確認%>
    <% if logged_in? %>
      <%= link_to '新規作成', new_middle_path, class: "navbar-item" %>
      <%= link_to 'プロフィール', user_path(current_user), class: "navbar-item" %>
      <%= link_to 'ランキング', rankings_middle_path, class: "navbar-item" %>
      <%= link_to 'ログアウト', logout_path, method: :delete, class: "navbar-item" %>
    <% else %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <strong>
            <%= link_to '新規登録画面', signup_path,data: {"turbolinks" => false}, class: "button is-primary" %>
          </strong>
          <%= link_to 'ログイン画面', login_path,data: {"turbolinks" => false}, class: "button is-light" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= render 'layouts/flash_messages' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiddleName</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= csrf_meta_tags %>

    <!--ナビバーのSCSS-->
    <%= stylesheet_link_tag "navbar", :media => "all" %>
    <!-- animate.css  -->
    <%= stylesheet_link_tag "animate", :media => "all" %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag('JapaneseMiddleName.ico') %>

  </head>
  <body>
    <%#ナビバーの表示位置%>
    <div class="bg">
      <%= render 'layouts/navbar' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>